
- name: installing nginx
  hosts : web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
      
  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: copy html file
    ansible.builtin.copy:
      content: "<h1>Hello</h1>"
      dest: /usr/share/nginx/html/index.html

  - name: create index.html
    ansible.builtin.copy:
        dest: /usr/share/nginx/html/index.html
        content: |
          <!DOCTYPE html>
          <html>
          <head>
              <title>Love Message</title>
          </head>
          <body style="text-align:center; background-color:black;">
              <h1 style="color:red; font-size:70px;">
                  i love u so much sadiqa
              </h1>
          </body>
          </html>


  