
- name: installing nginx
  hosts : web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
      tasks:
  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started
      enable: yes


