
- name: installing nginx
  hosts : web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
      
  - name: start service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: copy html file
    ansible.builtin.copy:
      content: "<h1>Hello from Ansible - Success</h1>"
      dest: /usr/share/nginx/html/index.html


